package net.javaguides.springboot.controller;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;

/**
 * Functional tests of StudentController and HelloWorldController generated by the test-skills
 * pipeline from the accepted case document TCDOC-step5-java-demo-9340016c revision 1
 * (cases TC-B1-001 .. TC-B1-012). Every request goes through MockMvc against the real
 * application context; the application keeps no state, so the context is shared by the class.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
@AutoConfigureMockMvc
class StudentControllerPipelineTest {

    private static final String APPLICATION_JSON = "application/json";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    // --- CAP-B1-mockmvc_exchange: one request, raw response ------------------------------

    private MockHttpServletResponse exchange(String method, String path, Map<String, String> query,
                                             Map<String, Object> jsonBody) throws Exception {
        MockHttpServletRequestBuilder request = MockMvcRequestBuilders.request(HttpMethod.valueOf(method), path);
        if (query != null) {
            for (Map.Entry<String, String> entry : query.entrySet()) {
                request = request.queryParam(entry.getKey(), entry.getValue());
            }
        }
        if (jsonBody != null) {
            request = request.contentType(MediaType.APPLICATION_JSON)
                    .content(objectMapper.writeValueAsString(jsonBody));
        }
        return mockMvc.perform(request).andReturn().getResponse();
    }

    private static String text(MockHttpServletResponse response) throws Exception {
        return response.getContentAsString(StandardCharsets.UTF_8);
    }

    private Map<String, Object> jsonObject(MockHttpServletResponse response) throws Exception {
        return objectMapper.readValue(text(response), new TypeReference<Map<String, Object>>() { });
    }

    private List<Map<String, Object>> jsonArray(MockHttpServletResponse response) throws Exception {
        return objectMapper.readValue(text(response), new TypeReference<List<Map<String, Object>>>() { });
    }

    private static Map<String, Object> student(Integer id, String firstName, String lastName) {
        Map<String, Object> student = new LinkedHashMap<>();
        student.put("id", id);
        student.put("firstName", firstName);
        student.put("lastName", lastName);
        return student;
    }

    private static List<Map<String, Object>> fourStudents() {
        return List.of(
                student(1, "Ramesh", "Mishra"),
                student(2, "Umesh", "Mishra"),
                student(3, "Ram", "Mishra"),
                student(4, "Sanjay", "Mishra"));
    }

    // --- cases --------------------------------------------------------------------------

    @Test
    @DisplayName("TC-B1-001 Получение фиксированного студента по GET /student")
    void tcB1001GetStudentReturnsFixedStudent() throws Exception {
        MockHttpServletResponse response = exchange("GET", "/student", null, null);

        assertThat(response.getStatus()).as("ASSERT-B1-001-01-1-1").isEqualTo(200);
        assertThat(response.getContentType()).as("ASSERT-B1-001-01-1-2").isEqualTo(APPLICATION_JSON);
        assertThat(jsonObject(response)).as("ASSERT-B1-001-01-1-3").isEqualTo(student(1, "Ramseh", "Mishra"));
        assertThat(text(response)).as("ASSERT-B1-001-01-1-4")
                .isEqualTo("{\"id\":1,\"firstName\":\"Ramseh\",\"lastName\":\"Mishra\"}");
    }

    @Test
    @DisplayName("TC-B1-002 Получение списка из четырёх студентов по GET /students")
    void tcB1002GetStudentsReturnsFourStudentsInOrder() throws Exception {
        MockHttpServletResponse response = exchange("GET", "/students", null, null);

        assertThat(response.getStatus()).as("ASSERT-B1-002-01-1-1").isEqualTo(200);
        assertThat(response.getContentType()).as("ASSERT-B1-002-01-1-2").isEqualTo(APPLICATION_JSON);
        List<Map<String, Object>> students = jsonArray(response);
        assertThat(students).as("ASSERT-B1-002-01-1-3").hasSize(4);
        assertThat(students).as("ASSERT-B1-002-01-1-4").isEqualTo(fourStudents());
    }

    @Test
    @DisplayName("TC-B1-003 Получение студента по идентификатору из пути GET /students/5")
    void tcB1003GetStudentByPathVariableReturnsRequestedId() throws Exception {
        MockHttpServletResponse response = exchange("GET", "/students/5", null, null);

        assertThat(response.getStatus()).as("ASSERT-B1-003-01-1-1").isEqualTo(200);
        assertThat(jsonObject(response)).as("ASSERT-B1-003-01-1-2").isEqualTo(student(5, "Ramsesh", "Mishra"));
    }

    @Test
    @DisplayName("TC-B1-004 Получение студента по идентификатору 0 из пути GET /students/0")
    void tcB1004GetStudentByPathVariableZeroIsAccepted() throws Exception {
        MockHttpServletResponse response = exchange("GET", "/students/0", null, null);

        assertThat(response.getStatus()).as("ASSERT-B1-004-01-1-1").isEqualTo(200);
        assertThat(jsonObject(response)).as("ASSERT-B1-004-01-1-2").isEqualTo(student(0, "Ramsesh", "Mishra"));
    }

    @Test
    @DisplayName("TC-B1-005 Получение студента по query-параметру GET /students/query?id=7")
    void tcB1005GetStudentByQueryParameterReturnsRequestedId() throws Exception {
        MockHttpServletResponse response = exchange("GET", "/students/query", Map.of("id", "7"), null);

        assertThat(response.getStatus()).as("ASSERT-B1-005-01-1-1").isEqualTo(200);
        assertThat(jsonObject(response)).as("ASSERT-B1-005-01-1-2").isEqualTo(student(7, "Ramesh", "Mishra"));
    }

    @Test
    @DisplayName("TC-B1-006 Отказ в запросе студента без обязательного параметра id GET /students/query")
    void tcB1006GetStudentWithoutIdParameterIsBadRequest() throws Exception {
        MockHttpServletResponse response = exchange("GET", "/students/query", Map.of(), null);

        assertThat(response.getStatus()).as("ASSERT-B1-006-01-1-1").isEqualTo(400);
    }

    @Test
    @DisplayName("TC-B1-007 Создание студента с полным JSON-телом POST /students/create")
    void tcB1007CreateStudentEchoesFullBodyWithCreated() throws Exception {
        Map<String, Object> body = student(5, "Ivan", "Petrov");

        MockHttpServletResponse response = exchange("POST", "/students/create", null, body);

        assertThat(response.getStatus()).as("ASSERT-B1-007-01-1-1").isEqualTo(201);
        assertThat(jsonObject(response)).as("ASSERT-B1-007-01-1-2").isEqualTo(student(5, "Ivan", "Petrov"));
    }

    @Test
    @DisplayName("TC-B1-008 Создание студента с частично заполненным телом без lastName POST /students/create")
    void tcB1008CreateStudentWithoutLastNameEchoesNull() throws Exception {
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("id", 6);
        body.put("firstName", "Olga");

        MockHttpServletResponse response = exchange("POST", "/students/create", null, body);

        assertThat(response.getStatus()).as("ASSERT-B1-008-01-1-1").isEqualTo(201);
        assertThat(jsonObject(response)).as("ASSERT-B1-008-01-1-2").isEqualTo(student(6, "Olga", null));
    }

    @Test
    @DisplayName("TC-B1-009 Обновление студента по PUT /students/10/update возвращает тело без подстановки id из пути")
    void tcB1009UpdateStudentEchoesBodyWithoutPathId() throws Exception {
        Map<String, Object> body = student(42, "Anna", "Sidorova");

        MockHttpServletResponse response = exchange("PUT", "/students/10/update", null, body);

        assertThat(response.getStatus()).as("ASSERT-B1-009-01-1-1").isEqualTo(200);
        assertThat(jsonObject(response)).as("ASSERT-B1-009-01-1-2").isEqualTo(student(42, "Anna", "Sidorova"));
    }

    @Test
    @DisplayName("TC-B1-010 Удаление студента по DELETE /students/3/delete возвращает подтверждающий текст")
    void tcB1010DeleteStudentReturnsConfirmationText() throws Exception {
        MockHttpServletResponse response = exchange("DELETE", "/students/3/delete", null, null);

        assertThat(response.getStatus()).as("ASSERT-B1-010-01-1-1").isEqualTo(200);
        assertThat(text(response)).as("ASSERT-B1-010-01-1-2").isEqualTo("Student Successfully Deleted!");
    }

    @Test
    @DisplayName("TC-B1-011 Получение приветствия по GET /hello-world")
    void tcB1011HelloWorldReturnsGreeting() throws Exception {
        MockHttpServletResponse response = exchange("GET", "/hello-world", null, null);

        assertThat(response.getStatus()).as("ASSERT-B1-011-01-1-1").isEqualTo(200);
        assertThat(text(response)).as("ASSERT-B1-011-01-1-2").isEqualTo("Hello World!");
    }

    @Test
    @DisplayName("TC-B1-012 Неизменность списка студентов после создания студента")
    void tcB1012StudentListIsUnchangedAfterCreate() throws Exception {
        // STEP-B1-012-01
        MockHttpServletResponse created = exchange("POST", "/students/create", null, student(9, "Pavel", "Orlov"));
        assertThat(created.getStatus()).as("ASSERT-B1-012-01-1-1").isEqualTo(201);
        assertThat(jsonObject(created)).as("ASSERT-B1-012-01-1-2").isEqualTo(student(9, "Pavel", "Orlov"));

        // STEP-B1-012-02
        MockHttpServletResponse afterCreate = exchange("GET", "/students", null, null);
        assertThat(afterCreate.getStatus()).as("ASSERT-B1-012-02-1-1").isEqualTo(200);
        assertThat(jsonArray(afterCreate)).as("ASSERT-B1-012-02-1-2").isEqualTo(fourStudents());

        // STEP-B1-012-03
        MockHttpServletResponse repeated = exchange("GET", "/students", null, null);
        assertThat(repeated.getStatus()).as("ASSERT-B1-012-03-1-1").isEqualTo(200);
        assertThat(jsonArray(repeated)).as("ASSERT-B1-012-03-1-2").isEqualTo(fourStudents());
    }
}
